"use client";

import Link from "next/link";
import {useState} from "react";
import {ArrowUpRight,Database,FileText,Flag,HelpCircle,MapPin,ShieldCheck,Sun,Mail,ChevronRight} from "lucide-react";
import {useApp} from "./provider";
import {useI18n} from "./i18n";
import {PageHeading,TrustBadge} from "./shared";
import {displayPlaceName} from "@/lib/catalog";

export function ContactPage(){const {t}=useI18n();return <main className="page-wrap info-page footer-info-page"><PageHeading eyebrow={t("footer.support")} title={t("footer.contactTitle")} description={t("footer.contactCopy")}><Link className="button secondary" href="/faq">{t("footer.viewFaq")} <ArrowUpRight size={15}/></Link></PageHeading><div className="info-grid"><section><HelpCircle/><h2>{t("footer.faq")}</h2><p>{t("footer.contactNote")}</p><Link className="text-link" href="/faq">{t("footer.contactFaq")} <ArrowUpRight size={15}/></Link></section><section><Flag/><h2>{t("footer.report")}</h2><p>{t("footer.reportCopy")}</p><Link className="text-link" href="/report">{t("footer.contactReport")} <ArrowUpRight size={15}/></Link></section><section><Mail/><h2>{t("footer.sourcesMethodology")}</h2><p>{t("common.factsSourcesCopy")}</p><Link className="text-link" href="/sources">{t("footer.methodology")} <ArrowUpRight size={15}/></Link></section></div><div className="service-note footer-honesty-note"><ShieldCheck size={20}/><div><strong>{t("footer.support")}</strong><p>{t("footer.contactNote")}</p></div></div></main>}

export function FaqPage(){const {t}=useI18n();const questions=[1,2,3,4,5] as const;return <main className="page-wrap info-page footer-info-page"><PageHeading eyebrow={t("footer.support")} title={t("footer.faqTitle")} description={t("footer.faqCopy")}><Link className="button secondary" href="/report">{t("footer.report")} <ArrowUpRight size={15}/></Link></PageHeading><div className="faq-list">{questions.map(number=><details key={number} open={number===1}><summary><span>{t(`footer.faqQ${number}`)}</span><ChevronRight size={17}/></summary><p>{t(`footer.faqA${number}`)}</p></details>)}</div></main>}

export function ReportPage(){const {catalog}=useApp();const {t,locale}=useI18n();const [placeId,setPlaceId]=useState(catalog.places[0]?.id??"");const [note,setNote]=useState("");const [submitted,setSubmitted]=useState(false);function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();try{window.localStorage.setItem("jeroam-report-draft",JSON.stringify({placeId,note,savedAt:new Date().toISOString()}));}catch{/* local persistence is best effort */}setSubmitted(true);}return <main className="page-wrap info-page footer-info-page"><PageHeading eyebrow={t("footer.support")} title={t("footer.reportTitle")} description={t("footer.reportCopy")}/>{submitted?<div className="service-note report-success" role="status"><TrustBadge tone="demo"/><ShieldCheck size={22}/><div><strong>{t("footer.reportSaved")}</strong><p>{t("footer.reportSavedCopy")}</p><button className="button secondary" type="button" onClick={()=>{setSubmitted(false);setNote("");}}>{t("footer.reportAnother")}</button></div></div>:<form className="report-form" onSubmit={submit}><TrustBadge tone="demo"/><label><span>{t("footer.reportPlace")}</span><select value={placeId} onChange={event=>setPlaceId(event.target.value)}>{catalog.places.map(place=><option value={place.id} key={place.id}>{displayPlaceName(place,locale)}</option>)}</select></label><label><span>{t("footer.reportNote")}</span><textarea required value={note} onChange={event=>setNote(event.target.value)} placeholder={t("footer.reportPlaceholder")} rows={7}/></label><div className="report-form-footer"><small>{t("footer.reportSavedCopy")}</small><button className="button" type="submit"><Database size={16}/>{t("footer.reportSubmit")}</button></div></form>}</main>}

export function TravelInformationPage(){const {t}=useI18n();return <main className="page-wrap info-page footer-info-page"><PageHeading eyebrow={t("footer.information")} title={t("footer.travelTitle")} description={t("footer.travelCopy")}><Link className="button secondary" href="/sources">{t("footer.sourcesMethodology")} <ArrowUpRight size={15}/></Link></PageHeading><div className="info-grid"><section><ShieldCheck/><h2>{t("footer.travelHours")}</h2><p>{t("footer.travelHoursCopy")}</p><Link className="text-link" href="/sources">{t("footer.sourcesMethodology")} <ArrowUpRight size={15}/></Link></section><section><MapPin/><h2>{t("footer.travelMap")}</h2><p>{t("footer.travelMapCopy")}</p><Link className="text-link" href="/explore">{t("footer.places")} <ArrowUpRight size={15}/></Link></section><section><Sun/><h2>{t("footer.travelWeather")}</h2><p>{t("footer.travelWeatherCopy")}</p><Link className="text-link" href="/">{t("home.rightNow")} <ArrowUpRight size={15}/></Link></section></div><section className="methodology" id="accessibility"><h2>{t("footer.accessibilityTitle")}</h2><p>{t("footer.accessibilityCopy")}</p><Link className="text-link" href="/sources">{t("footer.accessibilityLink")} <ArrowUpRight size={15}/></Link></section></main>}

type LegalKind="terms"|"privacy"|"cookies";
export function LegalPage({kind}:{kind:LegalKind}){const {t}=useI18n();const titleKey=kind==="terms"?"footer.termsTitle":kind==="privacy"?"footer.privacyTitle":"footer.cookiesTitle";const copyKey=kind==="terms"?"footer.termsCopy":kind==="privacy"?"footer.privacyCopy":"footer.cookiesCopy";const headingKey=kind==="terms"?"footer.termsHeading":kind==="privacy"?"footer.privacyHeading":"footer.cookiesHeading";const bodyKey=kind==="terms"?"footer.termsBody":kind==="privacy"?"footer.privacyBody":"footer.cookiesBody";return <main className="page-wrap info-page footer-info-page legal-page"><PageHeading eyebrow={t("footer.legal")} title={t(titleKey)} description={t(copyKey)}/><div className="demo-legal-note"><FileText size={20}/><strong>{t("footer.legalDemo")}</strong><span>{t("footer.legalNote")}</span></div><section className="methodology"><h2>{t(headingKey)}</h2><p>{t(bodyKey)}</p><div className="legal-links"><Link className="text-link" href="/sources">{t("footer.legalSources")} <ArrowUpRight size={14}/></Link><Link className="text-link" href="/">{t("footer.legalBack")} <ArrowUpRight size={14}/></Link></div></section></main>}
