"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Clock, Compass, Heart, Languages, Landmark, MapPin, Sparkles, UserRound, Users, Utensils } from "lucide-react";
import { useApp } from "./provider";
import { localeConfig, localizedLanguageName, useI18n } from "./i18n";
import { interests, languages, travelStyles, defaultPreferences, preferencesSchema, type Catalog, type Preferences } from "@/lib/contracts";
import { buildSuggestedTrip, pace } from "@/lib/planner";
import { displayPlaceName } from "@/lib/catalog";

const durationOptions = [1, 2, 3, 7, 10] as const;
const ageBands = [{ label: "0–5", value: 3 }, { label: "6–12", value: 9 }, { label: "13–17", value: 15 }, { label: "18–64", value: 30 }, { label: "65+", value: 70 }] as const;
const stepKeys = ["onboarding.who", "onboarding.duration", "onboarding.budget", "onboarding.travelers", "onboarding.interests", "onboarding.feeling", "onboarding.language"] as const;
function ageBand(age: number) { return age < 6 ? "0–5" : age < 13 ? "6–12" : age < 18 ? "13–17" : age >= 65 ? "65+" : "18–64"; }
function ageBandKey(label: string) { return label === "65+" ? "onboarding.ageBand.65-plus" : `onboarding.ageBand.${label.replace("–", "-")}`; }

export function Onboarding() {
  const { preferences, savePreferences, catalog, persistTrip, ready, user } = useApp();
  const { t } = useI18n();
  const router = useRouter();
  const editing = useSearchParams().get("edit") === "1";
  if (!ready) return <main className="page-wrap"><div className="loading-row"><span className="spinner" />{t("common.loading")}</div></main>;
  return <PreferenceWizard key={(preferences ? "existing" : "new") + "-" + editing} initial={preferences} editing={editing} cloud={!!user} catalog={catalog} onComplete={async (p) => { await savePreferences(p); await persistTrip(buildSuggestedTrip(catalog, p, Math.floor(Math.random() * 10000) + 1)); localStorage.removeItem("jeroam-onboarding-draft"); router.push(editing ? "/profile" : "/my-trip"); }} />;
}

function PreferenceWizard({ initial, editing, onComplete, cloud, catalog }: { initial: Preferences | null; editing: boolean; onComplete: (p: Preferences) => Promise<void>; cloud: boolean; catalog: Catalog }) {
  const { t, locale } = useI18n();
  const [step, setStep] = useState(0);
  const [draft, setDraft] = useState<Preferences>({ ...defaultPreferences, ...(initial ?? {}) });
  const [draftReady, setDraftReady] = useState(Boolean(initial));
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { if (initial) return; const timer = window.setTimeout(() => { try { const raw = localStorage.getItem("jeroam-onboarding-draft"); if (raw) { const parsed = JSON.parse(raw) as Partial<Preferences>; setDraft({ ...defaultPreferences, ...parsed, ages: Array.isArray(parsed.ages) && parsed.ages.length ? parsed.ages : defaultPreferences.ages, interests: Array.isArray(parsed.interests) ? parsed.interests : defaultPreferences.interests }); } } catch { /* keep defaults */ } setDraftReady(true); }, 0); return () => window.clearTimeout(timer); }, [initial]);
  useEffect(() => { if (draftReady && !editing) { try { localStorage.setItem("jeroam-onboarding-draft", JSON.stringify(draft)); } catch { /* storage is optional */ } } }, [draft, draftReady, editing]);
  const setValue = <K extends keyof Preferences>(key: K, value: Preferences[K]) => setDraft(current => ({ ...current, [key]: value }));
  const next = () => { setError(""); if (step === 4 && !draft.interests.length) { setError(t("onboarding.chooseInterest")); return; } if (step < 7) setStep(value => value + 1); };
  const back = () => { setError(""); setStep(value => Math.max(0, value - 1)); };
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (step < 6) { next(); return; } if (step === 6) { const parsed = preferencesSchema.safeParse(draft); if (!parsed.success) { const issue = parsed.error.issues[0]; setError(issue?.path.includes("ages") ? t("onboarding.ageError") : issue?.path.includes("people") ? t("onboarding.soloError") : t("onboarding.checkSelections")); return; } setStep(7); return; } setBusy(true); try { await onComplete(draft); } catch (caught) { setError(caught instanceof Error ? caught.message : t("common.tryAnother")); } finally { setBusy(false); } }
  const progress = Math.min(step + 1, 7);
  const selectedNames = draft.interests.slice(0, 3).map(item => t(`interest.${item}`)).join(" + ");
  const paceText = draft.travelStyle === "Packed with discoveries" ? t("onboarding.full") : pace(draft) === "relaxed" ? t("onboarding.slow") : t("onboarding.balanced");
  const previewPlaces = useMemo(() => { const ranked = catalog.places.filter(place => place.interests.some(item => draft.interests.includes(item as Preferences["interests"][number]))); return (ranked.length ? ranked : catalog.places).slice(0, 3); }, [catalog.places, draft.interests]);
  if (!draftReady) return <main className="onboarding-wrap"><div className="loading-row"><span className="spinner" />{t("common.loading")}</div></main>;
  const title = step < 7 ? t(stepKeys[step]) : t("onboarding.previewTitle");
  const intro = ["onboarding.groupHint", "onboarding.durationHint", "onboarding.budgetHint", "onboarding.travelersHint", "onboarding.interestsHint", "onboarding.feelingHint", "onboarding.languageHint"][step];
  const numberLocale = localeConfig[locale ?? "en"].htmlLang;
  const formatBudget = (value: number) => new Intl.NumberFormat(numberLocale, { style: "currency", currency: "ILS", maximumFractionDigits: 0 }).format(value);
  return <main className="onboarding-wrap onboarding-v2">
    <aside className="onboarding-aside"><img src="/images/tower-of-david.webp" alt={t("common.altTowerCourtyard")} /><div className="onboarding-aside-shade" /><section><span className="eyebrow light">{t("onboarding.eyebrow")}</span><h2>{t("onboarding.title")}</h2><p>{t("onboarding.copy")}</p><div className="aside-rule" /><span><MapPin size={15} />{t("common.jerusalemLayers")}</span><Link href="/credits">{t("common.photoBy",{credit:"Wayne McLean · CC BY 2.0"})}</Link></section></aside>
    <section className="onboarding-form onboarding-form-v2"><Link href={editing ? "/profile" : "/"} className="back-link"><ArrowLeft size={16} />{editing ? t("onboarding.myPreferences") : t("onboarding.backDiscover")}</Link>
      <div className="onboarding-progress"><div className="progress-meta"><span>{step < 7 ? t("onboarding.step", { current: String(Math.min(step + 1, 7)).padStart(2, "0") }) : t("onboarding.preview")}</span><strong>{step < 7 ? title : t("onboarding.ready")}</strong></div><div className="progress-track">{Array.from({ length: 7 }, (_, index) => <span className={index < progress ? "filled" : ""} key={index} />)}</div></div>
      {step < 7 ? <form onSubmit={submit}><div className="onboarding-kicker">{title}</div><h1>{title}</h1><p className="form-intro">{t(intro)}</p>
        {step === 0 && <fieldset className="choice-cards"><legend className="sr-only">{title}</legend>{([["Solo", UserRound, "onboarding.oneView"], ["Family", Heart, "onboarding.sharedDay"], ["Friends", Users, "onboarding.energy"]] as const).map(([name, Icon, copy]) => <button type="button" className={draft.tripType === name ? "selected" : ""} aria-pressed={draft.tripType === name} onClick={() => { setValue("tripType", name); if (name === "Solo") { setValue("people", 1); setValue("ages", [draft.ages[0] ?? 28]); } else if (draft.people < 2) { setValue("people", 2); setValue("ages", [draft.ages[0] ?? 28, draft.ages[1] ?? 12]); } }} key={name}><Icon size={28} /><strong>{t(`tripType.${name}`)}</strong><span>{t(copy)}</span>{draft.tripType === name && <Check size={16} />}</button>)}</fieldset>}
        {step === 1 && <div className="duration-grid">{durationOptions.map(value => <button type="button" className={draft.days === value ? "selected" : ""} aria-pressed={draft.days === value} onClick={() => setValue("days", value)} key={value}><strong>{t(`duration.${value}`)}</strong><span>{t(`durationHint.${value}`)}</span>{draft.days === value && <Check size={16} />}</button>)}</div>}
        {step === 2 && <div className="budget-step"><div className="budget-display"><span>{t("onboarding.dailyBudget")}</span><strong>{formatBudget(draft.budget)}</strong><small>{t("onboarding.perPerson")}</small></div><div className="budget-presets" role="group" aria-label="Budget presets">{[100, 200, 350, 500, 800, 1200].map(amt => <button type="button" key={amt} className={`budget-chip ${draft.budget === amt ? "active" : ""}`} onClick={() => setValue("budget", amt)}>{formatBudget(amt)}</button>)}</div><input className="budget-range" aria-label={t("onboarding.dailyBudget")} type="range" min="0" max="1500" step="50" value={Math.min(draft.budget, 1500)} onChange={event => setValue("budget", Number(event.target.value))} /><div className="range-labels"><span>{formatBudget(0)}</span><span>{formatBudget(1500)}+</span></div><label className="budget-input"><span>{t("onboarding.enterAmount")}</span><input type="number" min="0" max="10000" value={draft.budget} onChange={event => setValue("budget", Number(event.target.value) || 0)} /><small>{t("onboarding.ilsPerPerson")}</small></label><p className="small-note">{t("onboarding.budgetNote")}</p></div>}
        {step === 3 && <div className="travelers-step"><div className="people-control"><div><span className="eyebrow">{t("onboarding.travelingTogether")}</span><h3>{draft.people} {draft.people === 1 ? t("common.traveler") : t("common.travelers")}</h3><p>{t("onboarding.ageCopy")}</p></div><div className="quantity-control"><button type="button" aria-label={t("onboarding.removeTraveler")} disabled={draft.people <= 1} onClick={() => { const people = Math.max(1, draft.people - 1); setDraft(current => ({ ...current, people, ages: current.ages.slice(0, people) })); }}>−</button><span>{draft.people}</span><button type="button" aria-label={t("onboarding.addTraveler")} disabled={draft.people >= 20} onClick={() => { const people = Math.min(20, draft.people + 1); setDraft(current => ({ ...current, people, ages: [...current.ages, 18] })); }}>+</button></div></div><div className="age-list">{draft.ages.map((age, index) => <label key={index}><span>{t("common.traveler")} {index + 1}</span><select aria-label={`${t("common.traveler")} ${index + 1}`} value={ageBand(age)} onChange={event => { const value = ageBands.find(item => item.label === event.target.value)?.value ?? 30; setDraft(current => ({ ...current, ages: current.ages.map((currentAge, ageIndex) => ageIndex === index ? value : currentAge) })); }}>{ageBands.map(option => <option value={option.label} key={option.label}>{t(ageBandKey(option.label))}</option>)}</select></label>)}</div>{draft.tripType === "Family" && <div className="family-tip"><Heart size={16} /><span><strong>{t("onboarding.familyRhythm")}</strong> {t("onboarding.familyCopy")}</span></div>}</div>}
        {step === 4 && <div className="interest-grid">{interests.map(item => <button type="button" aria-pressed={draft.interests.includes(item)} className={draft.interests.includes(item) ? "selected" : ""} onClick={() => setDraft(current => ({ ...current, interests: current.interests.includes(item) ? current.interests.filter(value => value !== item) : [...current.interests, item] }))} key={item}><span>{t(`interest.${item}`)}</span>{draft.interests.includes(item) ? <Check size={16} /> : <span className="interest-plus">+</span>}</button>)}</div>}
        {step === 5 && <div className="feeling-grid">{travelStyles.map((style, index) => { const Icon = index === 0 ? Clock : index === 1 ? Compass : index === 2 ? Sparkles : index === 3 ? Utensils : index === 4 ? Landmark : MapPin; const hintKey = ["onboarding.slow", "onboarding.balanced", "onboarding.full", "onboarding.foodFirst", "onboarding.historyFirst", "onboarding.hidden"][index]; return <button type="button" className={draft.travelStyle === style ? "selected" : ""} aria-pressed={draft.travelStyle === style} onClick={() => setValue("travelStyle", style)} key={style}><Icon /><strong>{t(`style.${style}`)}</strong><span>{t(hintKey)}</span>{draft.travelStyle === style && <Check size={15} />}</button>; })}</div>}
        {step === 6 && <div className="language-grid">{languages.map(language => <button type="button" className={draft.language === language ? "selected" : ""} aria-pressed={draft.language === language} onClick={() => setValue("language", language)} key={language}><Languages size={20} /><strong>{language}</strong>{draft.language === language && <Check size={15} />}</button>)}</div>}
        {error && <p className="inline-error" role="alert">{error}</p>}<div className="form-actions onboarding-actions">{step > 0 && <button type="button" className="button secondary" onClick={back}><ArrowLeft size={16} />{t("common.back")}</button>}<button type="submit" className="button">{step === 6 ? t("onboarding.preview") : t("common.continue")}<ArrowRight size={17} /></button></div><p className="small-note">{cloud ? t("onboarding.savePrivate") : t("onboarding.saveAsGo")}</p>
      </form> : <div className="journey-preview"><div className="preview-icon"><Compass size={31} /></div><h1>{t("onboarding.previewTitle")}</h1><p>{t("onboarding.previewCopy")}</p><div className="preview-summary"><div><span className="eyebrow">{t("onboarding.yourTrip")}</span><strong>{draft.days} {draft.days === 1 ? t("common.day") : t("common.days")}</strong></div><div><span className="eyebrow">{t("onboarding.yourGroup")}</span><strong>{t(`tripType.${draft.tripType}`)} · {draft.people} {draft.people === 1 ? t("common.traveler") : t("common.travelers")}</strong></div><div><span className="eyebrow">{t("onboarding.yourLens")}</span><strong>{selectedNames || t("common.interests")}</strong></div><div><span className="eyebrow">{t("onboarding.yourFeeling")}</span><strong>{t(`style.${draft.travelStyle}`)}</strong></div><div><span className="eyebrow">{t("onboarding.yourPace")}</span><strong>{paceText}</strong></div><div><span className="eyebrow">{t("onboarding.yourLanguage")}</span><strong>{localizedLanguageName(draft.language,locale)}</strong></div></div><div className="preview-places"><span className="eyebrow">{t("onboarding.previewPlaces")}</span><div>{previewPlaces.map(place => <Link href={`/places/${place.id}`} key={place.id}><span>{t(`area.${place.area}`)}</span><strong>{displayPlaceName(place,locale)}</strong><ArrowUpRight size={15} /></Link>)}</div></div><div className="form-actions onboarding-actions"><button type="button" className="button secondary" onClick={back}><ArrowLeft size={16} />{t("common.adjust")}</button><button type="button" className="button" disabled={busy} onClick={() => void submit(new Event("submit") as unknown as FormEvent)}>{busy ? t("onboarding.building") : t("onboarding.build")}<ArrowRight size={17} /></button></div><p className="small-note">{t("onboarding.transparent")}</p></div>}
    </section>
  </main>;
}

