"use client";

import {ChevronDown} from "lucide-react";
import {useEffect,useId,useRef,useState,type KeyboardEvent as ReactKeyboardEvent, type ReactNode} from "react";

export type SwitcherOption<T extends string>={value:T;label:string;short?:string;icon?:ReactNode};

/** A compact, keyboard-friendly popover for global preference controls. */
export function Switcher<T extends string>({value,options,ariaLabel,onChange,icon,className=""}:{value:T;options:SwitcherOption<T>[];ariaLabel:string;onChange:(value:T)=>void;icon?:ReactNode;className?:string}){
 const [open,setOpen]=useState(false);const rootRef=useRef<HTMLDivElement>(null);const triggerRef=useRef<HTMLButtonElement>(null);const optionRefs=useRef<Array<HTMLButtonElement|null>>([]);const listId=useId();const active=options.find(option=>option.value===value)??options[0];
 useEffect(()=>{if(!open)return;const onPointerDown=(event:PointerEvent)=>{if(!rootRef.current?.contains(event.target as Node))setOpen(false);};const onKeyDown=(event:globalThis.KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);triggerRef.current?.focus();}};document.addEventListener("pointerdown",onPointerDown);document.addEventListener("keydown",onKeyDown);return()=>{document.removeEventListener("pointerdown",onPointerDown);document.removeEventListener("keydown",onKeyDown);};},[open]);
 function choose(next:T){onChange(next);setOpen(false);triggerRef.current?.focus();}
 function onTriggerKeyDown(event:ReactKeyboardEvent<HTMLButtonElement>){if(event.key==="ArrowDown"||event.key==="ArrowUp"||event.key==="Enter"||event.key===" "){event.preventDefault();setOpen(true);queueMicrotask(()=>optionRefs.current[Math.max(0,options.findIndex(option=>option.value===value))]?.focus());}}
 function onOptionKeyDown(event:ReactKeyboardEvent<HTMLButtonElement>,index:number){if(event.key==="ArrowDown"){event.preventDefault();optionRefs.current[(index+1)%options.length]?.focus();}else if(event.key==="ArrowUp"){event.preventDefault();optionRefs.current[(index-1+options.length)%options.length]?.focus();}else if(event.key==="Home"){event.preventDefault();optionRefs.current[0]?.focus();}else if(event.key==="End"){event.preventDefault();optionRefs.current[options.length-1]?.focus();}else if(event.key==="Escape"){event.preventDefault();setOpen(false);triggerRef.current?.focus();}else if(event.key==="Tab")setOpen(false);}
 return <div ref={rootRef} className={`switcher ${className}`.trim()}><button ref={triggerRef} type="button" className="switcher-trigger" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} aria-controls={listId} onClick={()=>setOpen(current=>!current)} onKeyDown={onTriggerKeyDown}>{icon&&<span className="switcher-icon" aria-hidden="true">{icon}</span>}<span className="switcher-value" data-short={active?.short??active?.label}>{active?.short??active?.label}</span><ChevronDown size={13} aria-hidden="true" className="switcher-chevron"/></button>{open&&<div id={listId} className="switcher-menu" role="listbox" aria-label={ariaLabel}>{options.map((option,index)=><button ref={element=>{optionRefs.current[index]=element;}} key={option.value} type="button" role="option" aria-selected={option.value===value} className={option.value===value?"selected":""} onClick={()=>choose(option.value)} onKeyDown={event=>onOptionKeyDown(event,index)}>{option.icon&&<span className="switcher-option-icon" aria-hidden="true">{option.icon}</span>}<span>{option.label}</span>{option.value===value&&<span className="switcher-check" aria-hidden="true">✓</span>}</button>)}</div>}</div>;
}
